name: Skan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    # Run every day at 16:00.
    - cron: '00 16 * * *'

jobs:
  skan:
    name: Skan
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - shell: julia --color=yes {0}
        run: 'using Pkg; Pkg.add(; url="https://github.com/rikhuijzer/Skans.jl#main")'

      - shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          using Skans
          repo = GitHubRepo()
          urls = [
              "http://example.com",
              "https://bbc.com"
          ]
          pages = WebPage.(urls)
          skan!(repo, pages)

