name: Skan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    # Run 16:00 UTC on Friday.
    - cron: '00 16 * * 5'

jobs:
  skan:
    name: Skan
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - shell: julia --color=yes {0}
        run: |
          using Pkg: develop
          develop(; path=pwd())

      - shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          using Skans
          repo = GitHubRepo()
          urls = [
              "http://example.com",
              "https://bbc.com"
          ]
          pages = WebPage.(urls)
          skan!(repo, pages)

